language: cpp
compiler: gcc
dist: xenial
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
  - sudo apt-get update
  - sudo apt-get -y install python python-pip
  - sudo pip install beautifulsoup4 lxml

install:
  - sudo apt-get install qt512base qt512websockets qt512serialport
  - source /opt/qt512/bin/qt512-env.sh
  - git clone --branch v1.12.2 https://github.com/qbs/qbs.git
  - cd qbs
  - git submodule init
  - git submodule update
  - qmake -r qbs.pro && make

script:
  - git clone https://github.com/Skarsnik/QUsb2snes.git
  - cd QUsb2snes
  - ../qsb/bin/qbs-setup-qt --detect
  - qbs profile:qt-5-12-0 build



