image: Visual Studio 2017

init:
  - set QTDIR=C:\Qt\5.12.1\msvc2017_64
  - set PATH=%PATH%;C:\Qt\5.12.1\msvc2017_64\bin;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
build_script:
  - qmake QUsb2snes.pro -spec win32-msvc "CONFIG+=release"
  - nmake
